<?php
return [
    'txt_faq_1' =>  'FAQ',
    'txt_faq_2' =>  'Curiosity, doubts, perplexity? targetcustomer.net answers!',
    'txt_faq_3' =>  'How many characters does the text of the SMS Advertising consist of?',
    'txt_faq_3_answer' =>  'The text must be within 150 characters. The targetCustomer platform will automatically insert a conclusive link-disclaimer of 10 characters to reach the 160 characters expected for an SMS. This link is required by law and allows the recipient of the message to verify the database in which his numbering is present and provides for a cancellation procedure. In the text are not recommended words in uppercase if not the name of the BRAND and the initials; furthermore, special characters are not accepted. like the symbols | ¥ ¿Ä Ä É Ñ Ö Ø Ü ß ä å æ ñ ö ø ü as they may not be correctly displayed by the recipient and therefore interfere with the comprehensibility of the message. It is possible to insert url or other links. The choice of text is an essential phase in the programming of the SMS Advertising campaign: read the information in the sectionGuidelines or ask for support from our Planning Advertising office or write your requests to advertising@rdcom.it .',
    'txt_faq_4' =>  'How many minimum SMS can I send per SMS Advertising campaign?',
    'txt_faq_4_answer'  =>  'It is possible to send Advertising campaigns starting from 1,000 SMS. This indication is used to have a representative pool of recipients to whom to direct the promotion and to have a return on its marketing action.',
    'txt_faq_5' =>  'From how many and what contacts is the targetCustomer Data Base made up of?',
    'txt_faq_5_answer'  =>  'The number of available contacts is constantly updated. targetCustomer is a web platform authorized to send bulk promotional SMS messages, called SMS Advertising. The service is offered to our customers using contacts that have given explicit consent to the sending of advertising sms: we are aware of the importance of operating in full compliance with the privacy protection laws [external link] , and for the satisfaction of our customers, and not to bother users who might receive unwanted information.',
    'txt_faq_6' =>  'Are there other possible profiles besides the standard ones? If yes, which ones?',
    'txt_faq_6_answer'  =>  'The targetCustomer database can also be used for profiling on contacts with VAT registration numbers. This extraction will be considered a priority and possible only on a minimal provincial basis. This request must be sent to our Planning Advertising office or by writing to the address targetcustomer.net .',
    'txt_faq_7' =>  'How can I be certain that the advertising campaign has been sent?',
    'txt_faq_7_answer'  =>  'After about 15 days from the date of delivery of the campaign, the sending certification will be uploaded online in the customer reserved area of ​​the platform. At the same time the report is sent to the e-mail address deposited by the customer upon registration to the service. The certificate summarizes the delivery date, the number of text messages sent, the requested target and the text of the message. The report can be simple or detailed depending on the type of campaign chosen (standard or customized). To verify the sending of the campaign it is possible to request the',
    'txt_faq_8' =>  'Is it possible to receive a text message when sending the Advertising campaign?',
    'txt_faq_8_answer'  =>  'Yes, at the time the campaign is created, the customer can request the insertion of one or more "owl" text messages (up to 5 contacts). Simply enter the users to whom you want to send in the "CAMPAIGN CREATION" section in the appropriate field.',
    'txt_faq_9' =>  'What times do I need to book an SMS Advertising campaign?',
    'txt_faq_9_answer'  =>  'Normally it is necessary to confirm the campaign at least 2 working days (48h) before the scheduled date of dispatch. This is to allow the Planning Advertising office to comply with internal campaign control and verification procedures. However, for campaigns sent using the standard or interactive sender mode, the delivery date must be checked at the time of planning, as it is bound by the daily availability limit.',
    'txt_faq_10'    =>  'Is it possible to customize the sender?',
    'txt_faq_10_answer'    =>  'Yes, sender customization is possible by choosing the type of campaign "with personalized sender". This type of campaign allows you to characterize the sender displayed by the recipient (max 11 characters). After 10 days from the sending a detailed report will be available with the number of SMS sent and the percentage of SMS actually delivered. The characters allowed to customize the sender are:! # $% "& () * +, / 0123456789:;<=> ? @ABCDEFGHIJKLMNOPQRSTUVWXYZ ^ _ £ ¥ §¿ÄÆÉÑÖØÜßàäåæèéñòöøùüìabcdefghijklmnopqrstuvwxyz . Sending with a personalized sender entails an increase in costs',
    'txt_faq_11'    =>  'What is an interactive SMS? Can the customer response be recorded?',
    'txt_faq_11_answer'    =>  'The advertising campaign with interactive SMS is a specific type of message that allows you to establish a direct relationship with the recipient. With this type of campaign it is possible to collect the numbers of the recipients who have accepted to be contacted to receive additional information regarding the offer received. The text of the message contains an offer and an invitation to reply to the SMS (by means of a definable syntax) to have access to the promotion or to the proposed service. The list (updated real time) of the numbers of recipients who have responded expressing their desire to be contacted is available and can be downloaded from the campaign summary. After 15 days from the provision of an interactive SMS campaign, a summary report is also issued to the customer as certification of the sending.',
    'txt_faq_12'    =>  'Can telephone numbers or links (multimedia content) be entered in the message text?',
    'txt_faq_12_answer'    =>  'Yes it is possible, there are no particular limitations on entering numbers or links to multimedia content in the text.',
    'txt_faq_13'    =>  'Is it possible to exclude from the profiling some locations that refer to a single CAP?',
    'txt_faq_13_answer'    =>  'No, the minimum profiling is based on the CAP. If a CAP contains more municipalities or localities, the extraction will take place on all the contacts contained in the indicated CAP.',
    'txt_faq_14'    =>  'What could be the reasons why my campaign was rejected?',
    'txt_faq_14_answer'    =>  'The SMS Advertising campaign can be refused if the internal controls carried out by our Planning Advertising office are not exceeded. The text of the message must not be offensive or damage human dignity; it cannot contain topics suitable only for "adults" (such as sex, pornography, child pornography, pedophilia); marks or elements used without a license or authorization must not be entered. The list presented here is to be considered exhaustive, but does not exclude that other arguments may lead to the suspension of the campaign. For internal policy more than one Advertising SMS per day is not sent to the same contact therefore, if the selected contacts are already the subject of other campaigns, the sending could be postponed to another delivery date. In the case of rejected campaigns, the Planning Advertising office will send the client a communication containing the reason.',
    'txt_faq_15'    =>  'What can be the causes of failure to deliver a message?',
    'txt_faq_15_answer'    =>  'Failure to deliver an SMS concerns isolated cases, with a small percentage value compared to the total number of messages sent. The most frequent causes are normally attributable to: poor coverage of the GSM network, incorrect recipient number, absence of the international prefix, setting of a sender with a number of characters in excess of what is allowed, errors attributable to the servers that manage queues and shipments , etc.',
    'txt_faq_16'    =>  'When is the invoice issued?',
    'txt_faq_16_answer'    =>  'The purchase invoice is issued after the purchase and registered according to the instructions given by the user when registering his account; these data can be modified and updated at any time in the INFO / USER DATA section. 
Starting from 01/01/2019, with the introduction of electronic invoicing (Law 205 of 27/12/2017), all the B2B reports will be sent in electronic format (XLM), through the interchange system to the recipient code (SDI), or to the PEC address expressly communicated or entered in the Business Register. 
For B2C reports and other situations not subject to this regulation (eg end consumers) a document is produced in PDF format, which will be sent to the email address indicated by the user in his account (section INFO / USER DATA) and made available in the same account (INFO / INVOICES section); this document contains the data relating to the purchase made (the same ones shown on the invoice) but will have no fiscal value.',


];